# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  via-ir = false
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 999
  out = "out"
  script = "scripts"
  solc = "0.8.27"
  src = "contracts"
  test = "test"
  cache_path  = "cache_forge"
  libs = ["node_modules", "lib"]
  gas_reports_ignore = ["MockToken"]
  fs_permissions = [{ access = "read", path = "scripts/bash-deploy/artifacts"}]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[profile.coverage]
  via-ir = false

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 160
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "${MAINNET_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"

  base = "${BASE_RPC_URL}"
  base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
  
  arbitrum = "${ARBITRUM_ONE_RPC_URL}"
  arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
  
  polygon = "${POLYGON_MAINNET_RPC_URL}"
  amoy = "${POLYGON_AMOY_RPC_URL}"

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
  sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
  
  base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
  base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

  arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
  arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
  
  polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
  amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }